### PR TITLE
Expose st2web in Vagrant

### LINKED ISSUE #28: Expose st2web access in Vagrant
Open access to st2web UI via Virtualbox port fowarding.
Apparently, it's easy to do, having control over the Vagrant template we ship with the `.box`.

### PR DESCRIPTION
**Pull request by armab**
Closes #28 

Make StackStorm web UI available via ~`https://127.0.0.1:9000/`~ `https://10.10.10.10/` for the host machine.

### TODO:
- [x] Implementation
  - [x] Verify
- [x] Print access details to stdout via Vagrantfile/ruby
- [x] Update st2docs

### CODE REVIEW

**Comment by LindsayHill** [comment]
9000 is an odd port to use. 
More common to use something like 8443 for an HTTPS service if you're not going to use 443.

**Comment by armab** [comment]
Yes, not going to use `443` since it has high chances to conflict with any existing host ports.

**Comment by armab** [comment]
In fact, it's a bad practice in Vagrant community to automatically port-forward anything by default via (parent) box Vagrantfile, except of SSH. Especially when it could conflict with user's Vagrantfile networking or host's existing ports so I'm not sure about this PR and postponed it for now as "optional'.

**Comment by LindsayHill** [comment]
I guess the main thing is that the user will want to be able to login to the Web UI. We have to make sure that the default Vagrant/Virtualbox configuration makes this easy.

I'm OK with the way we currently do it in github.com/StackStorm/st2vagrant, where we have a hard-coded IP. That at least makes documentation easy, and we're not forwarding ports, so that side should be OK.

Obviously a potential clash with someone using that network for something else, but there's a limit to what we can do here

**Comment by armab** [comment]
Alright, here is how it'll work: 

vagrant-up

**Pull request merged**
