### PR TITLE
Switch to Ubuntu 18.04 Bionic

### LINKED ISSUE #47: Switch from Ubuntu Xenial to Bionic
As part of the maintenance work, switch from `Ubuntu Xenial` which relies on py2 to `Ubuntu Bionic` with `python3` and MongoDB 4 for the Vagrant box we produce.

### PR DESCRIPTION
**Pull request by armab**
Closes #47 

As Ubuntu 16.04 support is deprecated, switch to Ubuntu 18.04.
The PR also includes Virtualbox guest addition changes to make them work in U18.

### CODE REVIEW

**Review by amanda11 — COMMENTED** [review]
Don't feel know enough on repo to give +1, but some feedback.

I'm not sure if some of the files in scripts need updating, eg

- scripts/welcome.sh still refers to U16
- should post-cleanup be cleaning up redis?

**Comment by armab** [comment]
@amanda11 These are very good finds, thanks a lot for that! :+1: Fixed now.
We could add redis to post-cleanup once we release the 3.5.0 as currently, it's not available in the stable version install.

**Review by amanda11 — APPROVED** [review]
LGTM, but would appreciate a +1 from another if possible.

**Comment by armab** [comment]
Merging, considering no other reviewers and tests are passing.

**Pull request merged**
