### PR TITLE
Updating Ubuntu ISO URL to 16.04.07

### PR DESCRIPTION
**Pull request by nmaludy**
old iso url doesn't exist anymore http://releases.ubuntu.com/16.04/ubuntu-16.04.6-server-amd64.iso

### CODE REVIEW

**Comment by nmaludy** [comment]
Closes #50

**Comment by armab** [comment]
BTW, looks like we install v3.2 as latest stable here, while the curl|bash script should install v3.3.
Created https://github.com/StackStorm/st2-packages/pull/667

**Comment by armab** [comment]
Additionally, need to finish the release pipeline to make sure v3.3 is the latest release in stackstorm/st2 as packer-st2 relies on that info.

**Comment by armab** [comment]
For more info, `VBoxService` startup binary is failing with the following:
```
vagrant@stackstorm:~$ sudo /usr/sbin/VBoxService
VBoxService 5.2.44 r139111 (verbosity: 0) linux.amd64 (Jul  9 2020 19:11:15) release log
00:00:00.000272 main     Log opened 2020-10-21T17:30:00.916107000Z
00:00:00.000378 main     OS Product: Linux
00:00:00.000464 main     OS Release: 4.4.0-193-generic
00:00:00.000520 main     OS Version: #224-Ubuntu SMP Tue Oct 6 17:15:28 UTC 2020
00:00:00.000625 main     Executable: /opt/VBoxGuestAdditions-5.2.44/sbin/VBoxService
00:00:00.000627 main     Process ID: 11316
00:00:00.000627 main     Package type: LINUX_64BITS_GENERIC
00:00:00.000764 main     Error: Failed to connect to the guest property service, rc=VERR_INTERNAL_ERROR
00:00:00.000825 main     Error: Service 'control' failed pre-init: VERR_INTERNAL_ERROR
```

**Review by armab — APPROVED** [review]
OK, Virtualbox build is fixed.
This should do it :+1:

**Comment by nmaludy** [comment]
LGTM, @armab  I can't approve this since it's my own PR

**Pull request merged**
